name: sEMG
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - torchaudio
  - tqdm
  - numpy
  - matplotlib
  - tensorboard
pip:
  - fastdtw